server.port=8090
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/jacaladev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=desarrollo